// agent-v2.js
// Executes the Playwright rules generated by discover.js with real tenant data.
//
// This file has no knowledge of form structure — it just loads form-plan.json
// (the ruleset discover.js keeps up to date) and runs it. If the council
// changes their form, discover.js rewrites the rules on its next run and this
// file executes the updated rules without any changes of its own.

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const FORM_URL = 'https://coa-microsite.vercel.app/';
const CANDIDATE_TOKEN = 'CAND-2026-292A';
const TMP_DIR = path.join(__dirname, 'tmp');
const PLAN_PATH = path.join(TMP_DIR, 'form-plan.json');

// Resolve a plan step's value: use moverField lookup if present, else use
// the static value, else fall back to the field name for upload/click steps.
function resolveValue(step, mover) {
  if (!step.moverField) return step.value;
  const key = step.moverField;
  if (key === 'candidateToken') return CANDIDATE_TOKEN;
  const val = mover[key];
  if (Array.isArray(val)) return val.join(', ');
  return String(val ?? '');
}

async function execute(page, step, documentPath, mover) {
  const value = resolveValue(step, mover);
  const nameOpt = { name: step.name, exact: step.exact ?? false };

  switch (step.action) {
    case 'click':
      if (step.role) {
        await page.getByRole(step.role, nameOpt).click();
      } else {
        await page.getByText(step.name, { exact: step.exact ?? false }).click();
      }
      break;
    case 'fill':
      await page.getByRole(step.role || 'textbox', nameOpt).fill(value);
      break;
    case 'select_option':
      await page.getByLabel(step.name).selectOption(value);
      break;
    case 'upload_file':
      await page.getByRole('button', { name: 'Upload a file' }).setInputFiles(documentPath);
      break;
    case 'submit':
    case 'done':
    case 'flag':
      return;
  }

  await page.waitForTimeout(400);
}

async function run(mover, documentPath, { dryRun = true } = {}) {
  if (!fs.existsSync(PLAN_PATH)) {
    throw new Error('No plan found at tmp/form-plan.json — run `node discover.js` first.');
  }

  const plan = JSON.parse(fs.readFileSync(PLAN_PATH, 'utf8'));
  console.log(`[agent-v2] Loaded plan: ${plan.length} actions from tmp/form-plan.json`);

  if (dryRun) {
    console.log('[agent-v2] Dry-run mode: will stop before submit.\n');
  }

  const browser = await chromium.launch({ headless: false, slowMo: 150 });
  const page = await browser.newPage();
  await page.goto(FORM_URL);

  for (let i = 0; i < plan.length; i++) {
    const step = plan[i];
    const value = resolveValue(step, mover);

    const desc = [
      step.action,
      step.role && step.name ? `${step.role}["${step.name}"]` : step.name,
      value ? `= "${value}"` : null,
    ].filter(Boolean).join(' ');

    // Dry-run guard: stop before the real submit action
    if (step.action === 'submit' && dryRun) {
      console.log(`[Step ${i + 1}/${plan.length}] DRY RUN — would submit here. Set DRY_RUN=false to submit for real.`);
      break;
    }

    console.log(`[Step ${i + 1}/${plan.length}] ${desc}`);

    if (step.action === 'done' || step.action === 'flag') {
      console.log('\n[agent-v2]', step.action === 'done' ? 'Completed.' : 'Flagged:', step.reason);
      break;
    }

    if (step.action === 'submit') {
      await page.getByRole('button', { name: 'Accept and submit' }).click();
      await page.waitForTimeout(1500);
      break;
    }

    await execute(page, step, documentPath, mover);
  }

  if (!fs.existsSync(TMP_DIR)) fs.mkdirSync(TMP_DIR);
  await page.screenshot({ path: path.join(TMP_DIR, 'agent-v2-final.png'), fullPage: true });
  console.log('\nFinal screenshot → tmp/agent-v2-final.png');

  await browser.close();
}

module.exports = { run };
